### ISSUE TITLE
1.12.2 Port 

### ISSUE THREAD

**Issue by RealmportalMC** [SugarCaney/CrystalQuest#4]
I am unable to use /cq setlobby. it tells me "Invalid command" I have had no other issues other than the one i just mentioned not teleporting people out after a game.

**Comment by SugarCaney** [comment]
~~Could you provide your config.yml, data.yml and stack traces in the console if there are any? Maybe also even screenshots.~~ 

Nvm, found the problem. SetLobby has not been registered as a command. fix coming soon.

**Comment by SugarCaney** [comment]
See build [v1.3.2](https://github.com/SugarCaney/CrystalQuest-1.12.2/releases/tag/v1.3.2)
