### ISSUE TITLE
Server throws IOException and sometimes stop responding when player join

### ISSUE THREAD

**Issue by MCUmbrella** [SugarCaney/CrystalQuest#6]
CQ version: 1.3.4
Server: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
latest.log: https://pastebin.com/PQDjsBYb

**Comment by SugarCaney** [comment]
Somehow the update checker couldn't read from the api request connection. If this keeps popping up  consider disabling update checking in the config.yml
